version: '3'

services:

  mysql:
    image: mysql:8.0.2
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: creditdb
    ports:
      - "3308:3306"
    volumes:
      - "./data:/var/lib/mysql:rw"
  credit-service:
    build:
      context: ./
      dockerfile: Dockerfile-credit-service
    image: credit-service
    ports:
      - 8081:8081
    networks:
      - network1
  product-service:
    build:
      context: ./
      dockerfile: Dockerfile-product-service
    image: product-service
    ports:
      - 8082:8082
    networks:
      - network1
  customer-service:
    build:
      context: ./
      dockerfile: Dockerfile-customer-service
    image: customer-service
    ports:
      - 8083:8083
    networks:
      - network1
 
networks:
  network1:
