version: '3'

services:

  mysql:
    image: mysql:8.0.2
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=creditdb
    ports:
      - "3308:3306"
    networks:
      credit-network:
        aliases:
          - mysql
    volumes:
      - "./data:/var/lib/mysql:rw"
  credit-service:
    build:
      context: ./
      dockerfile: Dockerfile-credit-service
    image: credit-service
    ports:
      - 8081:8081
    depends_on:
      - mysql
      - product-service
      - customer-service
    networks:
      credit-network:
        aliases:
          - credit-service
  product-service:
    build:
      context: ./
      dockerfile: Dockerfile-product-service
    image: product-service
    ports:
      - 8082:8082
    depends_on:
      - mysql
    networks:
      credit-network:
        aliases:
          - product-service
  customer-service:
    build:
      context: ./
      dockerfile: Dockerfile-customer-service
    image: customer-service
    ports:
      - 8083:8083
    depends_on:
      - mysql
    networks:
      credit-network:
        aliases:
          - customer-service
 
networks:
  credit-network:
